name: Behat Tests
on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT_LDAP: 3389
      PORT_LDAPS: 6363
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_LOG_LEVEL: 0
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3', '8.4']
        wordpress-version: ['6.2', '6.3', '6.4', '6.5', '6.6', '6.7', '6.8']

    name: Test on PHP ${{ matrix.php-version }}/WordPress ${{ matrix.wordpress-version }}
    steps:
      - uses: actions/checkout@v4
#      - name: Docker Compose Pull
#        run: docker compose pull
      - name: Cache Docker images
        id: docker-cache
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key:
            docker-${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.wordpress-version }}-${{ hashFiles('compose.yml') }}
      - name: Build the docker compose stack
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: docker compose build --build-arg PHP_VERSION=${{ matrix.php-version }} --build-arg WORDPRESS_VERSION=${{ matrix.wordpress-version }} wp
      - name: run the stack
        run: docker compose -f compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker compose logs openldap
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phive
          ini-values: "memory_limit=-1"
      - name: install dependencies
        run: composer install
      - name: install behat
        run: |
          composer require --dev behat/behat
      - name: run behat
        run: docker compose exec wp bash -c "cd wp-content/plugins/authldap && ./vendor/bin/behat"
      - name: Check logs
        if: ${{ failure() }}
        run: docker compose logs
